- name: setup vpc
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: import vpc variables
    include_vars: vars/vpc_setup

  - name: Create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      tags:
        Project: vprofile
      tenancy: default
      state: "{{state}}"
      dns_hostnames: yes
      dns_support: yes
    register: vpcout

  - name: Create public subnet 1 in zone 1
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub1Cidr}}"
      az: "{{zone1}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PubSub1
    register: pubsub1
    
      