- name: setup vpc
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: import vpc variables
    include_vars: vars/vpc_setup

  - name: Create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      tags:
        Project: vprofile
      tenancy: default
      state: "{{state}}"
      dns_hostnames: yes
      dns_support: yes
    register: vpcout

  - name: Create public subnet 1 in zone 1
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub1Cidr}}"
      region: "{{region}}"
      az: "{{zone1}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PubSub1
    register: pubsub1

  - name: Create public subnet 2 in zone 2
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub2Cidr}}"
      region: "{{region}}"
      az: "{{zone2}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PubSub2
    register: pubsub2

  - name: Create public subnet 3 in zone 3
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PubSub3Cidr}}"
      region: "{{region}}"
      az: "{{zone3}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PubSub3
    register: pubsub3

  - name: Create private subnet 1 in zone 1
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PvtSub1Cidr}}"
      region: "{{region}}"
      az: "{{zone1}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PvtSub1
    register: pvtsub1

  - name: Create private subnet 2 in zone 2
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PvtSub2Cidr}}"
      region: "{{region}}"
      az: "{{zone2}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PvtSub2
    register: pvtsub2

  - name: Create private subnet 3 in zone 3
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      cidr: "{{PvtSub3Cidr}}"
      region: "{{region}}"
      az: "{{zone3}}"
      state: "{{state}}"
      map_public: yes
      tags:
        Name: PvtSub3
    register: pvtsub3

  - name: Create Internet Gateway for the public subnets
    ec2_vpc_igw:
      vpc_id: "{{vpcout.vpc.id}}"
      region: "{{region}}"
      state: "{{state}}"
      tags:
        Name: vprofile_IGW
    register: igw_out

  - name: setup route table for public subnets to the IGW
    ec2_vpc_route_table:
      vpc_id: "{{vpcout.vpc.id}}"
      region: "{{region}}"
      subnets:
        - "{{pubsub1.subnet.id}}"
        - "{{pubsub2.subnet.id}}"
        - "{{pubsub3.subnet.id}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{igw_out.gateway_id}}"
      tags:
        Name: vpro_RT_pubsub
    register: pub_RT_out

  - name: Create NAT GW for the private subnet and Allocate EIP
    ec2_vpc_nat_gateway:
      state: "{{state}}"
      subnet_id: "{{pubsub1.subnet.id}}"
      wait: yes
      region: "{{region}}"
      if_exist_do_not_create: yes
    register: natgw_out

  - name: setup route table for private subnet to the NAT GW
    ec2_vpc_route_table:
      vpc_id: "{{vpcout.vpc.id}}"
      region: "{{region}}"
      subnets:
        - "{{pvtsub1.subnet.id}}"
        - "{{pvtsub2.subnet.id}}"
        - "{{pvtsub3.subnet.id}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{natgw_out.nat_gateway_id}}"
      tags:
        Name: vpro_RT_pvtsub 
    register: pvt_RT_out
    
      